on:
  push:
  workflow_dispatch:

jobs:
  example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: sleep
        with:
          milliseconds: 500
      - name: Read time
        run: echo "Slept until ${{ steps.sleep.outputs.time }}"
